version: '3'
services:
  backend:
    build:
      context: ./app
      dockerfile: serverSide/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/clientSide/destinationImages:/app/clientSide/destinationImages # Access image folder
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    image: node:19
    working_dir: /app
    volumes:
      - ./app/clientSide:/app
    command: npx live-server --port=8080 --host=0.0.0.0
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    name: app-network
